services:
  postgres:
    image: postgres:latest
    container_name: is-project-postgres
    environment:
      POSTGRES_USER: s333291
      POSTGRES_PASSWORD: qwerty12345
      POSTGRES_DB: studs
    ports:
      - "15432:5432"
  backend:
    image: killreal777/is-project-backend:latest
    container_name: is-project-backend
    depends_on:
      - postgres
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - SPRING_DATASOURCE_URL=jdbc:postgresql://is-project-postgres:5432/studs
      - SPRING_DATASOURCE_USERNAME=s333291
      - SPRING_DATASOURCE_PASSWORD=qwerty12345
    ports:
      - "8080:8080"