@startuml
title <size:24>IsProjectApplication</size>

set separator none
top to bottom direction

<style>
  root {
    BackgroundColor: #ffffff
    FontColor: #444444
  }
</style>

!include <C4/C4>
!include <C4/C4_Context>
!include <C4/C4_Component>

System_Boundary("IsProjectApplication_boundary", "IsProjectApplication", $tags="") {
  Container_Boundary("IsProjectApplication.IsProjectApplication_boundary", "IsProjectApplication", $tags="") {
    Component(IsProjectApplication.IsProjectApplication.Trade, "Trade", $techn="Module", $descr="", $tags="", $link="")
    Component(IsProjectApplication.IsProjectApplication.Dock, "Dock", $techn="Module", $descr="", $tags="", $link="")
    Component(IsProjectApplication.IsProjectApplication.Production, "Production", $techn="Module", $descr="", $tags="", $link="")
    Component(IsProjectApplication.IsProjectApplication.Shared, "Shared", $techn="Module", $descr="", $tags="", $link="")
    Component(IsProjectApplication.IsProjectApplication.Storage, "Storage", $techn="Module", $descr="", $tags="", $link="")
  }

}

Rel(IsProjectApplication.IsProjectApplication.Trade, IsProjectApplication.IsProjectApplication.Shared, "depends on", $techn="", $tags="", $link="")
Rel(IsProjectApplication.IsProjectApplication.Trade, IsProjectApplication.IsProjectApplication.Storage, "uses", $techn="", $tags="", $link="")
Rel(IsProjectApplication.IsProjectApplication.Dock, IsProjectApplication.IsProjectApplication.Shared, "depends on", $techn="", $tags="", $link="")
Rel(IsProjectApplication.IsProjectApplication.Dock, IsProjectApplication.IsProjectApplication.Storage, "uses", $techn="", $tags="", $link="")
Rel(IsProjectApplication.IsProjectApplication.Production, IsProjectApplication.IsProjectApplication.Shared, "depends on", $techn="", $tags="", $link="")
Rel(IsProjectApplication.IsProjectApplication.Production, IsProjectApplication.IsProjectApplication.Storage, "uses", $techn="", $tags="", $link="")
Rel(IsProjectApplication.IsProjectApplication.Storage, IsProjectApplication.IsProjectApplication.Shared, "depends on", $techn="", $tags="", $link="")

SHOW_LEGEND(true)
hide stereotypes
@enduml