DROP TRIGGER IF EXISTS no_updates_resource ON resource;
DROP TRIGGER IF EXISTS no_updates_trade ON trade;
DROP TRIGGER IF EXISTS no_updates_trade_item ON trade_item;
DROP TRIGGER IF EXISTS no_updates_build_cost ON build_cost;
DROP TRIGGER IF EXISTS no_updates_build_cost_item ON build_cost_item;
DROP TRIGGER IF EXISTS no_updates_storage_module_blueprint ON storage_module_blueprint;
DROP TRIGGER IF EXISTS no_updates_production_module_blueprint ON production_module_blueprint;
DROP TRIGGER IF EXISTS no_updates_dock_module_blueprint ON dock_module_blueprint;
DROP TRIGGER IF EXISTS no_updates_production ON production;
DROP TRIGGER IF EXISTS no_updates_consumption ON consumption;
DROP TRIGGER IF EXISTS trade_policy_auto_create ON resource;
DROP TRIGGER IF EXISTS docking_spots_auto_create ON dock_module;
DROP TRIGGER IF EXISTS check_storage_capacity ON stored_resource;
DROP TRIGGER IF EXISTS storage_module_build_cost_check ON storage_module_blueprint;
DROP TRIGGER IF EXISTS production_module_build_cost_check ON production_module_blueprint;
DROP TRIGGER IF EXISTS dock_module_build_cost_check ON dock_module_blueprint;

DROP FUNCTION IF EXISTS prevent_updates();
DROP FUNCTION IF EXISTS create_trade_policy();
DROP FUNCTION IF EXISTS create_docking_spots();
DROP FUNCTION IF EXISTS get_total_free_space_in_storages();
DROP FUNCTION IF EXISTS get_free_space_in_storage(INT);
DROP FUNCTION IF EXISTS prevent_storage_overflow();
DROP FUNCTION IF EXISTS check_build_cost_unique_constraint();

DROP TABLE IF EXISTS docking_spot CASCADE;
DROP TABLE IF EXISTS dock_module CASCADE;
DROP TABLE IF EXISTS consumption CASCADE;
DROP TABLE IF EXISTS production CASCADE;
DROP TABLE IF EXISTS production_module CASCADE;
DROP TABLE IF EXISTS stored_resource CASCADE;
DROP TABLE IF EXISTS storage_module CASCADE;
DROP TABLE IF EXISTS dock_module_blueprint CASCADE;
DROP TABLE IF EXISTS production_module_blueprint CASCADE;
DROP TABLE IF EXISTS storage_module_blueprint CASCADE;
DROP TABLE IF EXISTS build_cost_item CASCADE;
DROP TABLE IF EXISTS build_cost CASCADE;
DROP TABLE IF EXISTS trade_item CASCADE;
DROP TABLE IF EXISTS trade CASCADE;
DROP TABLE IF EXISTS trade_policy CASCADE;
DROP TABLE IF EXISTS spaceship CASCADE;
DROP TABLE IF EXISTS account CASCADE;
DROP TABLE IF EXISTS users CASCADE;
DROP TABLE IF EXISTS resource CASCADE;